### PR TITLE
submitting show notes for E39

### PR DESCRIPTION
**Pull request by mary-grace**

### CODE REVIEW

**Comment by mary-grace** [comment]
alright. Jeremy and I dug into this tonight and I think I finally understand it! :-p Tomorrow morning I'll finish up the Disasters episode and ping you when it's done so you can accept the PR for these two. Going forward, I'll create a new branch per episode and submit each PR from there. Sorry for the trouble!

**Comment by mary-grace** [comment]
We should be all set with this now -- both Ep 37 & 39 are final from my side. Thanks for your patience! I'll push them through as new branches in the future.

-m.

**Comment by mattstratton** [comment]
This is showing that there are conflicts that need to be resolved before merging. I think you would need to sync your branch with our master first, but I am going to try to fix this myself by merging from your fork and then submitting it myself. Maybe. Heh.

**Comment by mattstratton** [comment]
OK, so I got this in. The problem was that there was a conflict in that I had edited the andrew episode to add some data, so git couldn't auto-merge it. Easily fixed though.

I suggest that you do a pull from our master to yours at some point in the near future, as there are quite a few things I've changed. They won't affect your PR's probably though :)

**Comment by mary-grace** [comment]
ugh. so sorry about that! I'm glad it got worked out :) I'll definitely
update mine before I do the next episode.

Also, I just realized that I had a complete & total brain fart, and on the
2nd half of the Disasters! episode I named "Mark" as "Mike". Do you want me
to go in and make the changes?

-m.

**Comment by mattstratton** [comment]
No worries. I fixed it in master.

**Comment by mary-grace** [comment]
awesome - thanks :)

-m.

**Pull request merged**
