### PR TITLE
Adding 134

### PR DESCRIPTION
**Pull request by bridgetkromhout**
Starting ep 134.

Still to do:
- [x] @mattstratton to correct pagerduty assets (there's a link to the summit, for example, here: https://github.com/arresteddevops/ado-hugo/blob/master/content/sponsor/pagerduty.md)
- [x] @mattstratton verify sponsors and order of sponsors on page
- [x] @mattstratton to check title/description/show notes
- [x] Bridget to record PD ad
- [x] Joe to finish editing and upload
- [x] Joe to upload copy of video to ADO youtube
- [x] Bridget to edit in the video link
- [x] Bridget to mark this PR ready for merge
- [x] @mattstratton to release when desired

### CODE REVIEW

**Comment by mattstratton** [comment]
FYI the sponsor links are setup in https://github.com/arresteddevops/ado-hugo/blob/ep134/static/_redirects


The old md files aren’t used anymore :)

**Comment by mattstratton** [comment]
That said, PD is sending me a new banner ad :)

**Comment by bridgetkromhout** [comment]
> The old md files aren’t used anymore :)

Ah, k.

**Comment by bridgetkromhout** [comment]
> That said, PD is sending me a new banner ad :)

Do we need to hold the ep for this? If so, we might want to go ahead with Cape Town instead today.

**Comment by mattstratton** [comment]
Banner is coming shortly :)

**Comment by bridgetkromhout** [comment]
@mattstratton if you wanna check the banner, show notes, etc: https://deploy-preview-413--arrested-devops.netlify.com/devopsdays-chicago-2019/

**Comment by bridgetkromhout** [comment]
Pagerduty asset(s) is the last thing I know of that needs to be changed before this can be merged (although @mattstratton may want to make other changes).

**Pull request merged**
