### PR TITLE
Rationalize and update Nathen's bios

### PR DESCRIPTION
**Pull request by nathenharvey**
Only need one bio and one image.

Signed-off-by: Nathen Harvey <nharvey@chef.io>

### CODE REVIEW

**Comment by mattstratton** [comment]
@bridgetkromhout has strong feels in this so I’d like her review.

**Comment by nathenharvey** [comment]
It's cool, I don't have strong feelings about it but was asked to make sure it's up-to-date for the recent episode.  If there's value in the historical evolution of the bios, feel free to keep them around as they were.  I'm happy to update the PR such that there are three different bios for me if that's what you prefer.

**Comment by bridgetkromhout** [comment]
Yeah, I'm big on preserving history. Updating so your most recent ep points to current info is fine. Feel free to make a "3" version.

**Comment by nathenharvey** [comment]
see #359

**Pull request closed without merging**
