### PR TITLE
Added Secure by Design episode

### PR DESCRIPTION
**Pull request by roswellington**
Episode page, guest pages, images added.

Still needs podcast file, episode number, and sponsors.

### CODE REVIEW

**Comment by mattstratton** [comment]
Couple thoughts:

- maybe move the updates/fixes for the Team Topologies to a separate PR so we can merge those right away and fix the issues
- It would be good to have a more descriptive title for this PR (more like "Add secure by design episode" or something)
- More of a general note for anyone thinking about merging this eventually - this episode needs to not launch before April 6, just to not have a major clump of episodes. No changes need to the PR about this; just a note while I'm thinking about it :)

**Comment by roswellington** [comment]
Thanks for the feedback- will do, and I'll let the guests know the timeframe.

**Comment by roswellington** [comment]
Weird, those updates for the Team Topologies were already merged from my previous pull request. I'm not sure why it's showing up here again in this one but those corrections have already been made.

**Comment by mattstratton** [comment]
yeah, maybe you need to rebase your local version?

**Comment by bridgetkromhout** [comment]
Hi, @roswellington - before we merge this, please pull in the changes from upstream master. Here's where the problem is visible; see all those missing commits where your fork is lagging behind?

Screen Shot 2020-04-09 at 8 18 43 AM

Here is what you need to do to fix it:

Change to the directory where you have ado-hugo checked out.
```
git checkout master
git pull upstream master
git push
```

Then when you go look at https://github.com/roswellington/ado-hugo it should say it is even with master.

**Comment by roswellington** [comment]
Hi @bridgetkromhout -

Thanks for the reminder, this is done.

**Comment by mattstratton** [comment]
I just updated with the podcast filename, episode number (note in the future, this field is required, please uncomment it when you know the number), description, and date.

Still need to update with sponsors.

**Comment by mattstratton** [comment]
I added the sponsors; please do not merge until we confirm with @joelaha that I added the right ones that match the audio :)

**Pull request merged**
